# task/project_model.py
# Model for Project records


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


    
class Project(models.Model):

    name    = models.CharField (max_length=40)
    client  = models.CharField (max_length=40)
    task    = models.CharField (max_length=40)
    date    = models.DateField (auto_now_add=True)  
    notes   = models.TextField (null=True)


    # Format a record as a string
    def __unicode__(self):
        return self.name

    # Back trace a url to a view
    def get_absolute_url(self):
        return reverse('project-detail', kwargs={'pk': self.pk})

    # Object field handling
    def __iter__(self):
        for i in self.fields():
            yield (i, getattr(self, i))

    # Enumerate the fields
    def fields(self):
        return [ f.name for f in self._meta.fields ]

    # List of values
    def values(self):
        return [ v for f,v in self ]

    # Table of field labels and values
    def table(self):
        return zip(self.fields(),self.values())

