# brain/contact.py
# Model for Contact records


#############################################################################
# DO NOT EDIT THIS FILE
# This Code will be replaced by the code generator
#############################################################################

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

            
# Define a contact data type
class Contact(models.Model):
    
    name    = models.CharField (max_length=40)
    address = models.CharField (max_length=100)    
    phone   = models.CharField (max_length=15)
    user    = models.ForeignKey(User)
        
    # Format a record as a string
    def __unicode__(self):
        return self.name

    # Back trace a url to a view
    def get_absolute_url(self):
        return reverse('contact-detail', kwargs={'pk': self.pk})

    # Object field handling
    def __iter__(self):
        for i in self.fields():
            yield (i, getattr(self, i))

    # Enumerate the fields
    def fields(self):
        return [ f.name for f in self._meta.fields ]

    # List of values
    def values(self):
        return [ v for f,v in self ]

    # Table of field labels and values
    def table(self):
        return zip(self.fields(),self.values())

